# Generated by Django 3.2 on 2022-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220923_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountedPrice',
            new_name='MRP',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='discountedPrice',
            new_name='MRP',
        ),
    ]
