# Generated by Django 3.2 on 2022-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220923_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Percentage_Disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='variants',
            name='Percentage_Disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
