# Generated by Django 3.2 on 2022-09-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'हिंदी द्वारा')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी द्वारा')], max_length=6),
        ),
    ]
