# Generated by Django 3.2 on 2022-09-24 00:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
