# Generated by Django 3.2 on 2022-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/users/download.jpg', null=True, upload_to='images/users/'),
        ),
    ]
